baseURL = "https://ibu.kirjakovski.mk"
languageCode = "en-us"
title = "Prof. Kirjakovski IBU Blog"
theme = "hugo-theme-yinyang"
DefaultContentLanguage = "en"
pygmentsUseClasses = true
enableRobotsTXT = true

[languages]
  [languages.en]
    contentDir = "content"
    languageName = "English"
    weight = 1
    
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  authorHomepage = "https://ibu.kirjakovski.mk"
  author = "Atanas Kirjakovski"
  mainSections = ["posts"]
  headTitle = "Prof. Kirjakovski IBU Blog"
  deadline = ""